version: "3.2"

services:

    keepstar-php:
        image: murkyowl/keepstar-php:latest
        container_name: keepstar-php
        restart: always
        volumes:
        - "Keepstar-code:/var/www/Keepstar/"
        - type: bind
          source: ./config.php
          target: /var/www/Keepstar/config/config.php
        networks:
            - keepstar-network
    keepstar-nginx:
        image: murkyowl/keepstar-nginx:latest
        depends_on:
            - keepstar-php
        container_name: keepstar-nginx
        restart: always
        ports:
           - "${NGINX_HTTP}:80"
           - "${NGINX_HTTPS}:443"
        volumes:
           - "Keepstar-code:/var/www/Keepstar/"
        command: /bin/sh -c "envsubst '${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
        links:
           - keepstar-php
        networks:
           - keepstar-network



volumes:
     Keepstar-code:
networks:
    keepstar-network:


