version: "3.2"

services:

    keepstar-php:
        image: murkyowl/keepstar-php:latest
        container_name: keepstar-php
        restart: always
        volumes:
        - type: bind
          source: ./config.php
          target: /var/www/Keepstar/config/config.php
        networks:
            - keepstar-network
    keepstar-nginx:
        image: murkyowl/keepstar-nginx:latest
        container_name: keepstar-nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
             - Keepstar-code:/var/www/Keepstar/
        command: /bin/sh -c "nginx -g 'daemon off;'"
        links:
            - keepstar-php
        networks:
            - keepstar-network



volumes:
     Keepstar-code:
networks:
    keepstar-network:


